FROM python:{{config.python_version.value}}-slim
ENV PYTHONUNBUFFERED 1
WORKDIR /app/{{config.app_name}}
COPY ./requirements.txt /app/requirements.txt
RUN apt-get update -y
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/{{config.app_name}}
