FROM python:{{config.python_version.value}}-slim as builder

WORKDIR /app/{{config.app_name}}
COPY ./requirements.txt /app/requirements.txt
RUN pip install --user --no-cache-dir -r requirements.txt

COPY . /app/{{config.app_name}}

{% if config.framework == "fastapi" %}
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
{% endif %}